# GitHub Action Part1 - Basics

name: My-GitHubActions-Basics

on:
  push:
    branches: [ "main" ]
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: echo Hello, world!

  my_deploy:
    runs-on: ubuntu-latest
    #запуск второго джоба только после выполнения первого
    needs: my_testing
    steps:
      - name: Print Hello Message
        run: echo Hello World Deploy

     
