# GitHub Action Part1 - Basics

name: My-GitHubActions-Basics

# Задаём глобальные переменные
env:
  Application_name: "MyFlask"
  Package_name: "Flask-deploy-ver-${{ github.sha }}"
#устанавливаем тригер, пример при пуше в мейн  
on:
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run: echo Hello, world!
        
      - name: Execute few commands
        run: |
          echo Hello Message1
          echo Hello Message2
          echo "Application Name: ${{ env.Application_name }}"
          echo "Package Name: ${{ env.Package_name }}"
          
      - name: List current folder
        run: ls -la       
#копируем весь репозитори
      - name: Git clone my repo
        uses: actions/checkout@v1
        
      - name: List current folder
        run: ls -la 
  my_deploy:
    runs-on: ubuntu-latest
    # Запуск второго джоба только после выполнения первого
    needs: my_testing
    #Задаём переменные для этого джоба
    env:
      VAR1 : "This is job Level Variable1"
      VAr2 : "This is job Level Variable2" 
    steps:
      - name: Print Hello Message in Deploy
        run: echo Hello World Deploy

      - name: Print env vars
        run : |
          echo "Var1 = ${{ env. VAR1 }}"
          echo "Var2 = ${{ env. VAR2 }}"
          echo "Var3 = $Local_VAR"
          env:
            Local_VAR: "This supper local var" 
          
      - name: Show environment variables
        run: |
          echo "Application: ${{ env.Application_name }}"
          echo "Package: ${{ env.Package_name }}"
          
      - name: Lets some pakeges iof the are here1
        run: aws --version 
        
      - name: Lets some pakeges iof the are here2
        run: zip --version 
    
