# GitHub Action Part1 - Basics

name: My-GitHubActions-Basics

# Задаём глобальные переменные
env:
  Application_name: "MyFlask"
  Package_name: "Flask-deploy-ver-${{ github.sha }}"
  
on:
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run: echo Hello, world!
        
      - name: Execute few commands
        run: |
          echo Hello Message1
          echo Hello Message2
          echo "Application Name: ${{ env.Application_name }}"
          echo "Package Name: ${{ env.Package_name }}"

  my_deploy:
    runs-on: ubuntu-latest
    # Запуск второго джоба только после выполнения первого
    needs: my_testing
    steps:
      - name: Print Hello Message in Deploy
        run: echo Hello World Deploy
      
      - name: Show environment variables
        run: |
          echo "Application: ${{ env.Application_name }}"
          echo "Package: ${{ env.Package_name }}"
